FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /pigagent

COPY pigagent/pyproject.toml .
COPY pigagent/*.py .

RUN pip install --no-cache-dir .

CMD ["python", "main.py", "start"]
