FROM python:3.13-slim

WORKDIR /api

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcurl4-openssl-dev build-essential curl && \
    rm -rf /var/lib/apt/lists/*

COPY api/pyproject.toml .
RUN pip install --no-cache-dir .

COPY api/ .

COPY alembic/ ./alembic/
COPY alembic.ini .

CMD ["sh", "-c", "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"]
