FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /agent

COPY agent/pyproject.toml .
COPY agent/*.py .

RUN pip install --no-cache-dir .

CMD ["python", "main.py", "start"]
