apiVersion: apps/v1
kind: Deployment
metadata:
  name: pigugu-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pigugu-api
  template:
    metadata:
      labels:
        app: pigugu-api
    spec:
      serviceAccountName: pigugu-server-sa
      containers:
      - name: api
        image: 537557168531.dkr.ecr.us-west-1.amazonaws.com/pigugu-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pigugu-secrets
              key: DATABASE_URL
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: pigugu-secrets
              key: REDIS_URL
        - name: AWS_REGION
          value: "us-west-1"
        - name: AWS_IOT_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: pigugu-secrets
              key: AWS_IOT_ENDPOINT
        - name: AWS_IOT_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: pigugu-secrets
              key: AWS_IOT_WEBHOOK_SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: pigugu-api-service
spec:
  type: LoadBalancer
  selector:
    app: pigugu-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
