apiVersion: v1
kind: Secret
metadata:
  name: pigugu-secrets
type: Opaque
stringData:
  # Replace with your actual RDS endpoint
  DATABASE_URL: "__DATABASE_URL__"
  REDIS_URL: "redis://pigugu-redis.feoudk.ng.0001.usw1.cache.amazonaws.com:6379/0"
